"""Compatibility wrapper for the outbound PNCP client."""

from sherlock_holmes.adapters.outbound.pncp.client import (
    CONSULTA_BASE_URL,
    PNCP_BASE_URL,
    PNCP_FILE_BASE_URL,
    USER_AGENT,
    PncpApiError,
    PncpRequestResult,
    build_url,
    compact_digits,
    contract_detail_url,
    contract_file_download_url,
    contract_files_url,
    contract_publication_url,
    fetch_contract_files,
    fetch_contracts_by_publication,
    filter_records_by_terms,
    normalize_text,
    request_json,
)

__all__ = [
    "CONSULTA_BASE_URL",
    "PNCP_BASE_URL",
    "PNCP_FILE_BASE_URL",
    "USER_AGENT",
    "PncpApiError",
    "PncpRequestResult",
    "build_url",
    "compact_digits",
    "contract_detail_url",
    "contract_file_download_url",
    "contract_files_url",
    "contract_publication_url",
    "fetch_contract_files",
    "fetch_contracts_by_publication",
    "filter_records_by_terms",
    "normalize_text",
    "request_json",
]
